# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PropertyLookup.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'PropertyLookup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14PropertyLookup.proto\x12\x0ePropertyLookup\"(\n\nZipRequest\x12\x0b\n\x03zip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\" \n\x0b\x41\x64\x64ressList\x12\x11\n\taddresses\x18\x01 \x03(\t2X\n\x0ePropertyLookup\x12\x46\n\x0bLookupByZip\x12\x1a.PropertyLookup.ZipRequest\x1a\x1b.PropertyLookup.AddressListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PropertyLookup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ZIPREQUEST']._serialized_start=40
  _globals['_ZIPREQUEST']._serialized_end=80
  _globals['_ADDRESSLIST']._serialized_start=82
  _globals['_ADDRESSLIST']._serialized_end=114
  _globals['_PROPERTYLOOKUP']._serialized_start=116
  _globals['_PROPERTYLOOKUP']._serialized_end=204
# @@protoc_insertion_point(module_scope)
